{% set name = "metaflow-netflixext" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a06f9a4a328aecfeb56bfbe799bc888a76bfeb7f0999467b84105e5be3265353

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - metaflow >=2.12.29

test:
  imports:
    - metaflow_extensions.netflix_ext
    - metaflow_extensions.netflix_ext.cmd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Metaflow extensions from Netflix
  home: https://github.com/Netflix/metaflow-nflx-extensions
  dev_url: https://github.com/Netflix/metaflow-nflx-extensions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PertuyF
    - romain-intel
