{% set name = "metaflow-netflixext" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aff66bd7ddb5f7133f8dddfb079aa6defcaf5666f6deef67b9320c085191c31b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - metaflow >=2.10.0

test:
  imports:
    - metaflow_extensions.netflix_ext
    - metaflow_extensions.netflix_ext.cmd
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Metaflow extensions from Netflix
  home: https://github.com/Netflix/metaflow-nflx-extensions
  dev_url: https://github.com/Netflix/metaflow-nflx-extensions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PertuyF
    - romain-intel
